version: "3"
services:
  backend-node:
    container_name: "backend-node"
    build:
      context: Dockerfile.dev
      target: builder
    ports:
      - "3008:3008"
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
